import type { BlogPost } from './types'

/**
 * Заготовки будущих статей. Тела нет — страница такой статьи отдаёт
 * «не найдено», в списке блога они не показываются. Чтобы опубликовать:
 * создать файл в posts/, добавить импорт в index.tsx и убрать запись отсюда.
 */
export const DRAFTS: BlogPost[] = [
  // Farmina (13)
  {
    slug: 'farmina-nd-prime',
    title: 'Farmina N&D Prime — беззерновой холистик',
    excerpt: '',
    categories: ['Питание', 'Сравнения кормов'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'farmina-nd-ancestral',
    title: 'Farmina N&D Ancestral Grain: спельта и овёс',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'farmina-nd-ocean',
    title: 'Farmina N&D Ocean: рыбные рационы',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'farmina-nd-pumpkin',
    title: 'Farmina N&D Pumpkin: зачем тыква',
    excerpt: '',
    categories: ['Питание', 'Здоровье'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'farmina-nd-quinoa',
    title: 'Farmina N&D Quinoa: функциональные рационы',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'farmina-vet-life',
    title: 'Farmina Vet Life: гид по ветеринарным диетам',
    excerpt: '',
    categories: ['Ветдиеты'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'vet-life-mochekamennaya',
    title: 'Vet Life Urinary при МКБ',
    excerpt: '',
    categories: ['Ветдиеты', 'Здоровье'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'vet-life-gastro',
    title: 'Vet Life Gastrointestinal при чувствительном ЖКТ',
    excerpt: '',
    categories: ['Ветдиеты', 'Здоровье'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'farmina-sterilizovannye',
    title: 'Farmina для стерилизованных кошек',
    excerpt: '',
    categories: ['Кошки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'farmina-proizvodstvo',
    title: 'Где производят Farmina',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'farmina-original-fakes',
    title: 'Как отличить оригинальный Farmina от подделки',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'farmina-pozhilye-koshki',
    title: 'Farmina для пожилых кошек',
    excerpt: '',
    categories: ['Кошки', 'Здоровье'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'farmina-pozhilye-sobaki',
    title: 'Farmina для пожилых собак',
    excerpt: '',
    categories: ['Собаки', 'Здоровье'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  // Monge (14)
  {
    slug: 'monge-lineyki-podrobno',
    title: 'Обзор линеек Monge',
    excerpt: '',
    categories: ['Питание', 'Сравнения кормов'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'monge-bwild',
    title: 'Monge BWild',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'monge-monoprotein',
    title: 'Monge Monoprotein',
    excerpt: '',
    categories: ['Питание', 'Здоровье'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'monge-vetsolution',
    title: 'Monge VetSolution',
    excerpt: '',
    categories: ['Ветдиеты'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'monge-speciality',
    title: 'Monge Speciality Line',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'monge-kotyata',
    title: 'Monge для котят',
    excerpt: '',
    categories: ['Кошки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'monge-shchenki-mini',
    title: 'Monge для щенков mini',
    excerpt: '',
    categories: ['Собаки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'monge-shchenki-medium',
    title: 'Monge для щенков medium',
    excerpt: '',
    categories: ['Собаки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'monge-shchenki-maxi',
    title: 'Monge для щенков maxi',
    excerpt: '',
    categories: ['Собаки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'monge-sterilizovannye',
    title: 'Monge для стерилизованных',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'monge-lakomstva',
    title: 'Лакомства Monge Gift',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'monge-pozhilye',
    title: 'Monge для пожилых собак',
    excerpt: '',
    categories: ['Собаки', 'Здоровье'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'monge-vetsolution-mochekam',
    title: 'VetSolution Urinary',
    excerpt: '',
    categories: ['Ветдиеты', 'Здоровье'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'monge-italia',
    title: 'Monge: итальянское производство',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  // Сравнения (9)
  {
    slug: 'farmina-nd-vs-bwild',
    title: 'Farmina N&D или Monge BWild',
    excerpt: '',
    categories: ['Сравнения кормов'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'vet-life-vs-vetsolution',
    title: 'Vet Life или VetSolution',
    excerpt: '',
    categories: ['Сравнения кормов', 'Ветдиеты'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'farmina-vs-hills',
    title: 'Farmina или Hill\'s',
    excerpt: '',
    categories: ['Сравнения кормов'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'monge-vs-happy-dog',
    title: 'Monge или Happy Dog',
    excerpt: '',
    categories: ['Сравнения кормов'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'holistic-vs-superpremium',
    title: 'Холистик или суперпремиум',
    excerpt: '',
    categories: ['Сравнения кормов', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'forza10',
    title: 'Корма Forza10',
    excerpt: '',
    categories: ['Питание', 'Сравнения кормов'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'happy-dog-happy-cat',
    title: 'Happy Dog и Happy Cat',
    excerpt: '',
    categories: ['Сравнения кормов'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'hills-science-vs-prescription',
    title: 'Hill\'s Science Plan и Prescription Diet',
    excerpt: '',
    categories: ['Сравнения кормов', 'Ветдиеты'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'pochemu-italyanskie-korma',
    title: 'Почему итальянские корма в топе',
    excerpt: '',
    categories: ['Сравнения кормов'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  // Здоровье (18)
  {
    slug: 'gipoallergennyy-sobaka',
    title: 'Гипоаллергенный корм для собак',
    excerpt: '',
    categories: ['Здоровье', 'Собаки'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'chuvstvitelnyy-zhkt-koshka',
    title: 'Чем кормить кошку с чувствительным пищеварением',
    excerpt: '',
    categories: ['Здоровье', 'Кошки'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'chuvstvitelnyy-zhkt-sobaka',
    title: 'Корм для собак с чувствительным ЖКТ',
    excerpt: '',
    categories: ['Здоровье', 'Собаки'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'mkb-koshka',
    title: 'Корм для кошек при МКБ',
    excerpt: '',
    categories: ['Здоровье', 'Кошки', 'Ветдиеты'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'pochki-koshka',
    title: 'Корм для кошек при болезнях почек',
    excerpt: '',
    categories: ['Здоровье', 'Кошки', 'Ветдиеты'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'sustavy-sobaka',
    title: 'Корм для собак с проблемами суставов',
    excerpt: '',
    categories: ['Здоровье', 'Собаки', 'Ветдиеты'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'sherst-koshka',
    title: 'Корм для выведения шерсти у кошек',
    excerpt: '',
    categories: ['Здоровье', 'Кошки'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'kozha-sherst',
    title: 'Корм для здоровья кожи и шерсти',
    excerpt: '',
    categories: ['Здоровье'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'pohudenie-koshka',
    title: 'Как помочь кошке похудеть',
    excerpt: '',
    categories: ['Здоровье', 'Кошки'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'lishnyy-ves-sobaka',
    title: 'Лишний вес у собаки',
    excerpt: '',
    categories: ['Здоровье', 'Собаки'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'diabet-koshka',
    title: 'Чем кормить кошку при диабете',
    excerpt: '',
    categories: ['Здоровье', 'Кошки', 'Ветдиеты'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'pechen-korm',
    title: 'Корм при заболеваниях печени',
    excerpt: '',
    categories: ['Здоровье', 'Ветдиеты'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'sterilizaciya-koshka-posle',
    title: 'Питание кошки после стерилизации',
    excerpt: '',
    categories: ['Здоровье', 'Кошки'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'kastraciya-koty',
    title: 'Корм для кастрированных котов',
    excerpt: '',
    categories: ['Здоровье', 'Кошки'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'monobelkovyy',
    title: 'Монобелковый корм',
    excerpt: '',
    categories: ['Здоровье', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'bezzernovoy-mify',
    title: 'Беззерновой корм: мифы и правда',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'veterinarnye-diety',
    title: 'Ветеринарные диеты: когда назначают',
    excerpt: '',
    categories: ['Ветдиеты', 'Здоровье'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'pischevaya-allergiya',
    title: 'Пищевая аллергия или непереносимость',
    excerpt: '',
    categories: ['Здоровье', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  // Базовые вопросы (15)
  {
    slug: 'skolko-korma-koshka',
    title: 'Сколько корма давать кошке в день',
    excerpt: '',
    categories: ['Питание', 'Кошки'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'skolko-korma-sobaka',
    title: 'Сколько корма давать собаке',
    excerpt: '',
    categories: ['Питание', 'Собаки'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'perevod-sobaki-na-korm',
    title: 'Как перевести собаку на другой корм',
    excerpt: '',
    categories: ['Питание', 'Собаки'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'sostav-korma',
    title: 'Как читать состав корма',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'klassy-kormov',
    title: 'Классы кормов: эконом, премиум, суперпремиум, холистик',
    excerpt: '',
    categories: ['Питание', 'Сравнения кормов'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'khranenie-korma',
    title: 'Как хранить сухой корм',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'srok-godnosti',
    title: 'Срок годности корма',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'koshka-ne-est',
    title: 'Кошка не ест корм: причины',
    excerpt: '',
    categories: ['Питание', 'Кошки'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'sobaka-ne-est',
    title: 'Собака отказывается от корма',
    excerpt: '',
    categories: ['Питание', 'Собаки'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'smeshat-korma',
    title: 'Можно ли смешивать корма разных брендов',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'voda-suhoy-korm',
    title: 'Сколько воды нужно кошке на сухом корме',
    excerpt: '',
    categories: ['Питание', 'Кошки'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'lakomstva-skolko',
    title: 'Лакомства: сколько давать',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'pozhilaya-koshka-7plus',
    title: 'Корм для пожилой кошки 7+',
    excerpt: '',
    categories: ['Питание', 'Кошки', 'Здоровье'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'pozhilaya-sobaka-senior',
    title: 'Корм для пожилой собаки',
    excerpt: '',
    categories: ['Питание', 'Собаки', 'Здоровье'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'beremennost-kormlenie',
    title: 'Чем кормить беременную и кормящую кошку',
    excerpt: '',
    categories: ['Питание', 'Кошки'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  // Породы (15)
  {
    slug: 'britanskaya-koshka',
    title: 'Чем кормить британскую кошку: особенности породы и рациона',
    excerpt: '',
    categories: ['Кошки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'meyn-kun',
    title: 'Чем кормить мейн-куна: особенности породы и рациона',
    excerpt: '',
    categories: ['Кошки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'sfinks',
    title: 'Чем кормить сфинкса: особенности породы и рациона',
    excerpt: '',
    categories: ['Кошки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'shotlandskaya-vislouhaya',
    title: 'Чем кормить шотландскую вислоухую: особенности и рацион',
    excerpt: '',
    categories: ['Кошки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'bengalskaya',
    title: 'Чем кормить бенгальскую кошку: особенности породы и рациона',
    excerpt: '',
    categories: ['Кошки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'shpic',
    title: 'Чем кормить шпица: особенности породы и рациона',
    excerpt: '',
    categories: ['Собаки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'francuzskiy-buldog',
    title: 'Чем кормить французского бульдога: особенности и рацион',
    excerpt: '',
    categories: ['Собаки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'nemeckaya-ovcarka',
    title: 'Чем кормить немецкую овчарку: особенности и рацион',
    excerpt: '',
    categories: ['Собаки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'chihuahua',
    title: 'Чем кормить чихуахуа: особенности мелкой породы и рациона',
    excerpt: '',
    categories: ['Собаки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'persidskaya-koshka',
    title: 'Чем кормить персидскую кошку: особенности и рацион',
    excerpt: '',
    categories: ['Кошки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'sibirskaya-koshka',
    title: 'Чем кормить сибирскую кошку: особенности и рацион',
    excerpt: '',
    categories: ['Кошки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'abissinskaya',
    title: 'Чем кормить абиссинскую кошку: особенности и рацион',
    excerpt: '',
    categories: ['Кошки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'ragdoll',
    title: 'Чем кормить рэгдолла: особенности и рацион',
    excerpt: '',
    categories: ['Кошки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'dvor-koshka',
    title: 'Чем кормить дворняжку: питание беспородной кошки',
    excerpt: '',
    categories: ['Кошки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'korm-melkiye-sobaki',
    title: 'Корм для собак мелких пород',
    excerpt: '',
    categories: ['Собаки', 'Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  // Доверие (6)
  {
    slug: 'svezhie-sroki',
    title: 'Почему важны свежие сроки годности и целая упаковка',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'deshevyy-korm',
    title: 'Чем опасен дешёвый корм',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'naturalka-na-suhoy',
    title: 'Как перевести питомца с натуралки на сухой корм',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'chto-nelzya',
    title: 'Что нельзя давать кошкам и собакам со стола',
    excerpt: '',
    categories: ['Питание', 'Здоровье'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'menyat-vkusy',
    title: 'Нужно ли менять вкусы корма',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
  {
    slug: 'chek-list-vladeltsa',
    title: 'Чек-лист осознанного владельца',
    excerpt: '',
    categories: ['Питание'],
    date: '2026-08-02',
    readingMinutes: 0,
    status: 'draft',
    metaTitle: '',
    metaDescription: '',
  },
]
